-- One-time cleanup: align stored `video.category` values with `lib/schemas.ts` `videoCategories`.
-- Run in Supabase SQL editor after inspecting distinct values:
--   SELECT category, COUNT(*) FROM video GROUP BY category ORDER BY COUNT(*) DESC;
--
-- Edit the WHEN clauses to match strings actually present in your DB, then uncomment and run.

-- Example renames (duplicate/adjust as needed):
-- UPDATE video SET category = 'Education & Tutorials', "updatedAt" = NOW() WHERE category = 'Education';
-- UPDATE video SET category = 'AI & Tech', "updatedAt" = NOW() WHERE category IN ('Tech', 'Technology');
-- UPDATE video SET category = 'Other', "updatedAt" = NOW() WHERE category NOT IN (
--   'AI & Tech','ASMR & Relaxation','Art & Creative','Beauty & Fashion','Business & Finance',
--   'Cars & Automotive','Comedy','DIY & Crafts','Education & Tutorials','Entertainment',
--   'Food & Cooking','Gaming','Health & Wellness','Motivational','Music','Nature & Wildlife',
--   'News & Commentary','Parenting & Family','Podcasts & Interviews','Reviews & Unboxing',
--   'Science & Documentary','Shorts & Clips','Sports & Fitness','Travel & Lifestyle','Other'
-- );
